spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:mysql://localhost:3306/spring_api?createDatabaseIfNotExist=true
    username: root
    password: "yes"
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 5 minutes
    refreshTokenExpiration: 604800 # 7 days